
package iniciodesesion;

import java.awt.Color;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {


    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baground = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        contra_txt = new javax.swing.JPasswordField();
        PANEL_login = new javax.swing.JPanel();
        label_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        baground.setBackground(new java.awt.Color(255, 255, 255));
        baground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen20.png"))); // NOI18N
        baground.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 340, 300));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/loginIcon.png"))); // NOI18N
        baground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 280, 270));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pngtree-original-vector-red-and-black-variegated-abstract-brushstrokes-background-image_527864.jpg"))); // NOI18N
        jLabel1.setDoubleBuffered(true);
        baground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 630));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setText("iniciar sesión");
        baground.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 160, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel5.setText("Usuario:");
        baground.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        baground.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 330, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("Contraseña:");
        baground.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        txt_usuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(204, 204, 204));
        txt_usuario.setText("Ingrese su nombre de usuario");
        txt_usuario.setBorder(null);
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuarioMousePressed(evt);
            }
        });
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        baground.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 330, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        baground.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 330, -1));

        contra_txt.setForeground(new java.awt.Color(204, 204, 204));
        contra_txt.setText("********");
        contra_txt.setBorder(null);
        contra_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contra_txtMousePressed(evt);
            }
        });
        baground.add(contra_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 330, 20));

        PANEL_login.setBackground(new java.awt.Color(204, 0, 0));
        PANEL_login.setForeground(new java.awt.Color(255, 255, 255));

        label_login.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        label_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_login.setText("INGRESAR");
        label_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PANEL_loginLayout = new javax.swing.GroupLayout(PANEL_login);
        PANEL_login.setLayout(PANEL_loginLayout);
        PANEL_loginLayout.setHorizontalGroup(
            PANEL_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_login, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        PANEL_loginLayout.setVerticalGroup(
            PANEL_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_login, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        baground.add(PANEL_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baground, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(baground, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void txt_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMousePressed
        if (txt_usuario.getText().equals("Ingrese su nombre de usuario")) {
            txt_usuario.setText("");
            txt_usuario.setForeground(Color.black);
        }
        if (String.valueOf(contra_txt.getPassword()).isEmpty()) {
            contra_txt.setText("*********");
            txt_usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_usuarioMousePressed

    private void contra_txtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contra_txtMousePressed
        // TODO add your handling code here:
        if (String.valueOf(contra_txt.getPassword()).equals("********")) {
            contra_txt.setText("");
            contra_txt.setForeground(Color.black);
        }
        if (txt_usuario.getText().isEmpty()) {
            txt_usuario.setText("Ingrese su nombre de usuario");
            txt_usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_contra_txtMousePressed

    private void label_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_loginMouseClicked
        // TODO add your handling code here:
        label_login.setBackground(new Color(200,220,255));
        String contrasena, usuario;
        usuario = txt_usuario.getText();
        contrasena = contra_txt.getText();
        if (usuario.equals("programacion") && contrasena.equals("123")){
            frame2 a = new frame2();
            a.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Usuario y/o contraseña incorrectos");
        }
                
    }//GEN-LAST:event_label_loginMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PANEL_login;
    private javax.swing.JPanel baground;
    private javax.swing.JPasswordField contra_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel label_login;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
